#!/bin/bash
# build.sh — build and install vk_flip_meter layer (v3.0)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
INSTALL_PREFIX="${1:-/usr/local}"
NATIVE_BUILD="${FLM_NATIVE_BUILD:-OFF}"

echo "==> Building vk_flip_meter (v3.0)"
echo "    Prefix: $INSTALL_PREFIX"
if [ "$NATIVE_BUILD" = "ON" ]; then
    echo "    Native build: ON (-O3 -march=native -mtune=native -flto, runs on this machine only)"
fi
echo ""

# Vulkan header check
if [ ! -f /usr/include/vulkan/vulkan.h ] && \
   [ ! -f /usr/local/include/vulkan/vulkan.h ]; then
    echo "ERROR: Vulkan headers not found."
    echo "       Gentoo: sudo emerge -av media-libs/vulkan-loader"
    exit 1
fi

if ! find /usr/include /usr/local/include -name "vk_layer.h" 2>/dev/null | grep -q .; then
    echo "ERROR: vk_layer.h not found."
    echo "       Gentoo: sudo emerge -av media-libs/vulkan-layers"
    exit 1
fi

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Prefer Ninja when available
if command -v ninja >/dev/null 2>&1; then
    GENERATOR="Ninja"
    BUILD_CMD="ninja -j$(nproc)"
    INSTALL_CMD="sudo ninja install"
else
    echo "==> ninja not found, using Unix Makefiles"
    GENERATOR="Unix Makefiles"
    BUILD_CMD="make -j$(nproc)"
    INSTALL_CMD="sudo make install"
fi

cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
    -DCMAKE_INSTALL_LIBDIR="lib64" \
    -DFLM_NATIVE_BUILD="$NATIVE_BUILD" \
    -G "$GENERATOR"

$BUILD_CMD

echo ""
echo "==> Installing (may need sudo)"
$INSTALL_CMD

# [FIX-52] The manifest is now generated by CMake configure_file with the
# correct path+version; no post-install sed patching needed.

echo ""
echo "==> Install complete. Verify:"
echo "    vulkaninfo --summary | grep -i flip_meter"
echo ""
echo "============================================================"
echo " QUICK VERIFICATION (2-second proof the layer is active)"
echo "============================================================"
echo ""
echo "  # FPS cap: MangoHud should show a flat 60 FPS line (works on every driver)."
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_TARGET_FPS=60 mangohud %command%"
echo ""
echo "============================================================"
echo " USAGE (v3.0 — auto-configuring)"
echo "============================================================"
echo ""
echo "  # Default: FPS cap if FLM_TARGET_FPS>0, otherwise the floor pacer wherever"
echo "  # it can help (presentWait + MAILBOX/IMMEDIATE, or FIFO with a VRR cadence)."
echo "  # MFG multiplier, floor ratio, spin margin, hitch handling: all automatic."
echo "  ENABLE_LAYER_cpu_flip_meter=1 %command%"
echo ""
echo "  # Input lag first (looser floor, shorter hitch recovery):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=latency %command%"
echo ""
echo "  # FPS cap:"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_TARGET_FPS=120 %command%"
echo ""
echo "  # Live readout every 5 s (avg/p99, hitch count, mfg, effective ratio):"
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_LOG_LEVEL=INFO FLM_STATS=1 FLM_LOG_FILE=/tmp/flm.log %command%"
echo ""
echo "============================================================"
echo " A/B TEST"
echo "============================================================"
echo ""
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_MODE=off FLM_CSV=/tmp/off.csv %command%"
echo "  ENABLE_LAYER_cpu_flip_meter=1               FLM_CSV=/tmp/on.csv  %command%"
echo ""
echo "============================================================"
echo " LIVE TUNING (FLM_MODE, FLM_TARGET_FPS, FLM_FLOOR_RATIO, FLM_LOG_LEVEL)"
echo "============================================================"
echo ""
echo "  ENABLE_LAYER_cpu_flip_meter=1 FLM_CONFIG=/tmp/flm.conf %command%"
echo "  echo 'FLM_MODE=latency' > /tmp/flm.conf && kill -USR1 \$(pgrep -f game_name)"
echo ""
echo "  # Build with native optimizations (this machine only, not portable):"
echo "  FLM_NATIVE_BUILD=ON ./build.sh"
echo ""
